const TICKET_ID_PREFIX = 'TID-';
const COMPLAINT_ID_PREFIX ='CID';
const REFUND_ID_PREFIX = 'RID-';
const INVOICE_ID_PREFIX = 'IID-';
const STUDENT_ID_PREFIX = 'SID-';
module.exports = {
    TICKET_ID_PREFIX,
    COMPLAINT_ID_PREFIX,
    REFUND_ID_PREFIX,
    INVOICE_ID_PREFIX,
    STUDENT_ID_PREFIX,
}

